modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MC-U-Team/Attack-Speed-Enchantment/issues"
displayURL="https://u-team.info/mods/attackspeedenchantment"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="attackspeedenchantment"
	version="${file.jarVersion}"
	displayName="Attack Speed Enchantment"
	updateJSONURL="https://api.u-team.info/update/attackspeedenchantment.json"
	description="This mod adds an enchantment that allows you to decrease the attack speed."
	
	[[dependencies.attackspeedenchantment]]
	    modId="forge"
	    mandatory=true
	    versionRange="[31.2.27,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.attackspeedenchantment]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.attackspeedenchantment]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.0.0.159-SNAPSHOT,)"
	    ordering="NONE"
	    side="BOTH"